wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1676487217.660691
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.13.10
      8:
      - 5
absorbing_state:
  desc: null
  value: false
acq_weight:
  desc: null
  value: 2.0
algo:
  desc: null
  value: GAIL
alpha:
  desc: null
  value: 0.2
automatic_entropy_tuning:
  desc: null
  value: false
batch_size:
  desc: null
  value: 256
bo_gp_mean:
  desc: null
  value: Zero
co_adapt:
  desc: null
  value: false
cuda:
  desc: null
  value: false
disc_warmup:
  desc: null
  value: 20000
disc_weight_decay:
  desc: null
  value: 1.0e-05
dist_optimizer:
  desc: null
  value: null
env_name:
  desc: null
  value: GaitTrackHalfCheetahOriginal-v0
episodes_per_morpho:
  desc: null
  value: 5
eval:
  desc: null
  value: true
expert_demos:
  desc: null
  value: demos/expert_demos.pt
expert_env_name:
  desc: null
  value: null
expert_episode_length:
  desc: null
  value: 300
expert_legs:
  desc: null
  value:
  - 0
  - 1
expert_markers:
  desc: null
  value:
  - 1
  - 2
  - 3
explore_morpho_episodes:
  desc: null
  value: 800
fixed_morpho:
  desc: null
  value: null
gamma:
  desc: null
  value: 0.99
head_type:
  desc: null
  value: null
head_wrt:
  desc: null
  value: null
hidden_size:
  desc: null
  value: 256
learn_disc_transitions:
  desc: null
  value: false
load_warmup:
  desc: null
  value: false
log_scale_rewards:
  desc: null
  value: false
lr:
  desc: null
  value: 0.0003
morpho_warmup:
  desc: null
  value: 60000
normalize_obs:
  desc: null
  value: false
num_steps:
  desc: null
  value: 1000001
omit_done:
  desc: null
  value: false
policy:
  desc: null
  value: Gaussian
policy_legs:
  desc: null
  value:
  - 0
  - 1
policy_markers:
  desc: null
  value:
  - 1
  - 2
  - 3
pos_type:
  desc: null
  value: norm
q_weight_decay:
  desc: null
  value: 1.0e-05
record_test:
  desc: null
  value: false
replay_size:
  desc: null
  value: 2000000
resume:
  desc: null
  value: null
reward_style:
  desc: null
  value: GAIL
run_name:
  desc: null
  value: gail
save_checkpoints:
  desc: null
  value: false
save_morphos:
  desc: null
  value: false
seed:
  desc: null
  value: 123456
start_steps:
  desc: null
  value: 10000
subject_id:
  desc: null
  value: 8
target_entropy:
  desc: null
  value: auto
target_update_interval:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.005
torso_type:
  desc: null
  value: null
train_distance_value:
  desc: null
  value: false
train_every:
  desc: null
  value: 1
updates_per_step:
  desc: null
  value: 1
vae_scaler:
  desc: null
  value: 1.0
vel_type:
  desc: null
  value: rel
