---
defaults:
  - base_gen_obs
  - _self_

num_obs: 10000
env_name: GaitTrack2segHalfCheetah-v0
resume: /scratch/work/hernans2/cosil/models/final/half-cheetah-2seg/GaitTrack2segHalfCheetah-v0/seed-123456/demonstrator_1700092284.pt
#resume: /scratch/work/hernans2/cosil/models/final/humanoid/GaitTrackHumanoid-v0/seed-123456/demonstrator_1700092365.pt
save_path: /scratch/work/hernans2/cosil/data/demos/

logger:
  project_name: "cosil-demos"
  group_name: "2segHalfCheetah"
  experiment_name: "gen_demos"
  run_id: ""
  loggers: console,wandb
