---
defaults:
  - base_gen_obs
  - _self_

num_obs: 10000
env_name: GaitTrackHalfCheetahOriginal-v0
resume: models/optimal/expert/GaitTrackHalfCheetahOriginal-v0/123456/1683291577.pt
save_path: data/
