---
defaults:
  - base_gen_obs
  - _self_

num_trajectories: 10 # cheetah
#num_trajectories: 40 # humanoid
# env_name: GaitTrackHumanoid-v0
# resume: /scratch/work/hernans2/cosil/final/humanoid/GaitTrackHumanoid-v0/seed-111/demonstrator_1702874491.pt
#env_name: GaitTrackHumanoid-v0
env_name: GaitTrackHalfCheetah36-v0
#resume: /scratch/work/hernans2/cosil/final/humanoid/GaitTrackHumanoid-v0/seed-123456/demonstrator_1709747996.pt
#resume: /scratch/work/hernans2/cosil/final/humanoid/GaitTrackHumanoid-v0/seed-42/demonstrator_1710521294.pt
resume: /scratch/work/hernans2/cosil/final/half-cheetah36/GaitTrackHalfCheetah36-v0/seed-123456/demonstrator-hc36_1712000712.pt
# env_name: GaitTrack2segHalfCheetah-v0
# resume: /scratch/work/hernans2/cosil/models/final/half-cheetah-2seg/GaitTrack2segHalfCheetah-v0/seed-123456/demonstrator_1700092284.pt
save_path: /scratch/work/hernans2/cosil/data/demos/
saved_agent_name: agent
saved_morpho_name: morphos
learn_disc_transitions: false
morpho_in_state: true
absorbing_state: false # humanoid
# absorbing_state: false

method:
  eval_periodically: false
  batch_size: 256
  updates_per_step: 1
  start_steps: 0
  replay_capacity: 2000000
  replay_dim_ratio: 0.9999
  record_test: false
  record_path: /scratch/work/hernans2/cosil/videos
  save_checkpoints: false
  save_optimal: false
  save_final: false
  sparse_mask: null
  #rm_action_penalty: false # humanoid
  rm_action_penalty: false

  # Humanoid
  #pos_type: norm
  #vel_type: rel
  #expert_legs: [0, 1, 2, 3]
  #policy_legs: [0, 1, 2, 3]
  #expert_markers: [0, 1, 2]
  #policy_markers: [0, 1, 2]
  #torso_type: null
  #head_type: null
  #head_wrt: null

  #HalfCheetah
  #pos_type: norm
  #vel_type: rel
  #expert_legs: [0, 1]
  #policy_legs: [0, 1]
  #expert_markers: [1, 2, 3]
  #policy_markers: [1, 2, 3]
  #torso_type: vel
  #head_type: null
  #head_wrt: null
  
  #HalfCheetah COIL
  pos_type: norm
  vel_type: rel
  expert_legs: [0, 1]
  policy_legs: [0, 1]
  expert_markers: [ 3]
  policy_markers: [ 3]
  torso_type: null
  head_type: null
  head_wrt: null
  
  # pos_type: norm
  # vel_type: rel
  # expert_legs: [0, 1]
  # policy_legs: [0, 1]
  # expert_markers: [1, 2]
  # policy_markers: [1, 2]
  # torso_type: null
  # head_type: null
  # head_wrt: null

  omit_done: false

logger:
  project_name: 'cosil-demos'
  group_name: 'halfcheetah'
  experiment_name: 'gen_demos'
  run_id: ''
  loggers: console
