---
defaults:
  - base_gen_buffer
  - override /method: coil
  - override /method/rewarder: env
  - override /method/agent: sac
  - _self_

env_name: GaitTrack2segHalfCheetah-v0
save_path: /scratch/work/hernans2/cosil/data/replay_buffers/individual/
device: cuda

method:
  eval_periodically: false
  save_final: false
  num_episodes: 20
  replay_capacity: 20000
  episodes_per_morpho: 200
  morpho_warmup: 0
  disc_warmup: 0

logger:
  run_id: ""
  loggers: console
