---
defaults:
  - base_gen_obs
  - _self_

num_obs: 10000
env_name: GaitTrackHalfCheetah-v0
resume: models/final/CoSIL/GaitTrackHalfCheetah-v0/seed-123456/demonstrator_1687515731.pt
save_path: data/demos/
