---
defaults:
  - base_pretrain
  - _self_

env_name: GaitTrackHalfCheetah-v0
device: cpu
updates: 50
models_dir_path: data/pretrained

method:
  replay_buffer_path: data/replay_buffers/merged/buffer_1686554160.pt
  norm_type: none

logger:
  project_name: CoSIL
  group_name: pretraining
  experiment_name: dual-sac-gailcrit
  loggers: console
