---
defaults:
  - base_train
  - _self_

env_name: GaitTrackHalfCheetah-v0

method:
  reset_omega: false
  num_episodes: 100
  morpho_warmup: 50000

  # CoIL
  episodes_per_morpho: 5

logger:
  project_name: "CoSIL-test"
  group_name: "11-05-2023_omega"
  experiment_name: "no-reset"
  run_id: ""
  loggers: console,file,wandb
