---
defaults:
  - base_train
  - _self_

device: cpu
env_name: GaitTrackHalfCheetah-v0

method:
  # reset_omega: true
  num_episodes: 2
  morpho_warmup: 0

  # CoIL
  episodes_per_morpho: 5

logger:
  project_name: "CoSIL-test"
  group_name: "11-05-2023_triton"
  experiment_name: "cpu"
  run_id: ""
  loggers: file,console
