---
defaults:
  - base_train
  - _self_

device: cpu
env_name: GaitTrackHalfCheetah-v0

method:
  num_episodes: 5
  eval_per_episodes: 2
  start_steps: 1000

  # CoIL
  episodes_per_morpho: 2
  morpho_warmup: 0
  disc_warmup: 0

  # CoSIL
  # reset_omega: true

logger:
  project_name: "CoSIL-test"
  group_name: "11-05-2023_triton"
  experiment_name: "cpu"
  run_id: ""
  loggers: file,console
